import Image from 'next/image'
import { ProtectedActionLink } from '@/components/protected-action-link'
import { SiteHeader } from '@/components/site-header'

import hauwaImage from '../../../../public/images/therapist-hauwa.png'

export function generateStaticParams() { return [{ slug: 'hauwa-ibrahim' }] }

export default function TherapistDetailPage() {
  const fact = 'min-h-[5.4rem] rounded-2xl border border-[#e1d9cc] bg-[#fffdf8] p-[1.3rem]'
  const label = 'text-[.7rem] tracking-[.08em] text-[#657167]'
  const slotButton = 'rounded-lg border border-[#e1d9cc] bg-[#fffdf8] px-[.65rem] py-[.35rem] text-xs text-[#334137]'
  return <main className="min-h-screen bg-[#fbf7ee] text-[#112f22]">
    <SiteHeader active="therapists" />
    <section className="mx-auto grid w-[min(1112px,calc(100%_-_2.5rem))] grid-cols-[minmax(0,1.25fr)_minmax(22rem,.82fr)] gap-8 pt-[.45rem] max-md:grid-cols-1 max-md:pb-8"><div><div className="flex items-start gap-5 max-md:items-center"><Image className="h-24 w-24 rounded-2xl object-cover" src={hauwaImage} alt="Hauwa Ibrahim" /><div><h1 className="mt-[.35rem] mb-[.2rem] font-[family-name:var(--happi-font-title)] text-4xl max-md:text-[1.75rem]">Hauwa Ibrahim</h1><p className="m-0 text-[.85rem] text-[#657167]">Counselling Psychologist · Kaduna, Nigeria</p><span className="mt-[.55rem] inline-block whitespace-nowrap rounded-full bg-[#f1ead3] px-[.7rem] py-[.35rem] text-xs text-[#174d33]">✓ Credentials verified · NACP/CP/2651</span></div></div><p className="my-7 max-w-[39rem] text-[1.03rem] leading-[1.6] text-[#4d5c51]">I focus on sleep difficulties, academic pressure and low mood, using grounded tools you can practice between sessions. My work is sensitive to faith, family and community contexts.</p><div className="grid grid-cols-2 gap-4 max-md:grid-cols-1"><article className={fact}><span className={label}>QUALIFICATION</span><p className="mt-[.65rem] text-[.86rem] leading-6">MSc Counselling Psychology, ABU Zaria</p></article><article className={fact}><span className={label}>SPECIALTIES</span><p className="mt-[.65rem] text-[.86rem] leading-6">Sleep, Student pressure, Low mood</p></article><article className={fact}><span className={label}>APPROACHES</span><p className="mt-[.65rem] text-[.86rem] leading-6">CBT-I, Mindfulness</p></article><article className={fact}><span className={label}>LANGUAGES</span><p className="mt-[.65rem] text-[.86rem] leading-6">English, Hausa</p></article><article className={fact}><span className={label}>CULTURAL EXPERIENCE</span><p className="mt-[.65rem] text-[.86rem] leading-6">Faith-sensitive practice, Academic pressure, Young adults</p></article><article className={fact}><span className={label}>EXPERIENCE</span><p className="mt-[.65rem] text-[.86rem] leading-6">6 years</p></article></div></div>
      <aside className="rounded-[1.25rem] border border-[#e1d9cc] bg-[#fffdf8] px-6 py-[1.7rem]"><h2 className="m-0 font-[family-name:var(--happi-font-title)] text-xl">Request a session</h2><strong className="mt-[.65rem] block text-[1.55rem] text-[#195438]">₦18,000</strong><p className="m-0 text-[.85rem] text-[#657167]">$35 international · 50-minute session</p><div className="my-6 mb-[.8rem] grid max-h-60 gap-[.55rem] overflow-y-auto"><span className={label}>THU, SEP 24</span><div className="mb-[.45rem] flex flex-wrap gap-2"><button className={slotButton}>6:00 PM</button><button className={slotButton}>6:50 PM</button><button className={slotButton}>7:40 PM</button></div><span className={label}>SAT, SEP 26</span><div className="mb-[.45rem] flex flex-wrap gap-2"><button className={slotButton}>10:00 AM</button><button className={slotButton}>10:50 AM</button><button className={slotButton}>11:40 AM</button><button className={slotButton}>12:30 PM</button></div><span className={label}>SUN, SEP 27</span><div className="mb-[.45rem] flex flex-wrap gap-2"><button className={slotButton}>2:00 PM</button><button className={slotButton}>2:50 PM</button><button className={slotButton}>3:40 PM</button><button className={slotButton}>4:30 PM</button></div></div><p className="mt-[.8rem] text-[.85rem] leading-[1.45] text-[#657167]">Availability shown in your timezone (Africa/Lagos (UTC+1)). Session types: Video.</p><ProtectedActionLink actionHref="/care?therapist=hauwa-ibrahim" className="mt-[1.2rem] block w-full rounded-[.35rem] bg-[#195438] p-3 text-center font-bold text-[#fffdf8] no-underline" href="/care?therapist=hauwa-ibrahim">Request this therapist</ProtectedActionLink><p className="mt-[.8rem] text-[.85rem] leading-[1.45] text-[#657167]">You send a booking request first — no payment is taken until Hauwa approves. Free reschedule up to 24 hours before a confirmed session.</p></aside></section>
  </main>
}
