import { SiteHeader } from '@/components/site-header'
import { TherapistPortalTabs } from '@/components/therapist-portal-tabs'

const steps = ['01 Personal information', '02 Professional background', '03 Practice & expertise', '04 Availability & rates', '05 Bio & photo', '06 Supporting documents']

export default function TherapistPortalPage() {
  const field = 'grid gap-[.35rem] text-[.85rem]'
  const input = 'min-h-[2.3rem] rounded-[.4rem] border border-[#e1d9cc] bg-[#fffdf8] px-[.7rem] py-[.55rem] text-[#112f22] shadow-[0_2px_3px_#382c1d12]'
  const card = 'rounded-[1.25rem] border border-[#e1d9cc] bg-[#fffdf8]'
  return <main className="min-h-screen bg-[#fbf7ee] text-[#112f22]"><SiteHeader active="therapists-portal" /><section className="mx-auto w-[min(1240px,calc(100%_-_2.5rem))] pt-[.55rem] pb-8 max-md:w-[calc(100%_-_2rem)]"><p className="mb-[.3rem] text-[.84rem] text-[#e5763d]">Therapist portal</p><h1 className="m-0 font-[family-name:var(--happi-font-title)] text-[2rem]">Practise on Happi</h1><span className="mt-[.45rem] block max-w-[58rem] text-[.9rem] leading-6 text-[#566458]">Apply → submit credentials → admin review → approval → your profile is published. Only approved professionals appear publicly.</span><strong className="mt-5 inline-block rounded-full bg-[#f1ede0] px-4 py-[.65rem] text-[.85rem] font-medium">Verification status: &nbsp; Not started</strong></section><div className="mx-auto w-[min(1240px,calc(100%_-_2.5rem))] max-md:w-[calc(100%_-_2rem)]"><TherapistPortalTabs active="application" /><div className="mt-6 grid grid-cols-[1.25fr_.9fr] gap-8 max-md:grid-cols-1 max-md:gap-4"><section className={`${card} p-6`}><div className="flex flex-wrap gap-[.55rem]">{steps.map((step, index) => <span className={`rounded-full px-3 py-[.4rem] text-[.73rem] ${index === 0 ? 'bg-[#195438] text-[#fffdf8]' : 'bg-[#f1ead3]'}`} key={step}>{step}</span>)}</div><form className="mt-7 grid gap-[1.2rem]"><label className={field}>Full name<input className={input} /></label><label className={field}>Email<input className={input} type="email" /></label><label className={field}>Phone number<input className={input} type="tel" /></label><label className={field}>Country of practice<input className={input} defaultValue="Nigeria" /></label><div className="flex gap-[.7rem]"><button className="rounded-[.4rem] border border-[#e1d9cc] bg-[#fffdf8] px-[.95rem] py-[.58rem] text-[#98a096]" type="button" disabled>Back</button><button className="rounded-[.4rem] border border-[#195438] bg-[#195438] px-[.95rem] py-[.58rem] font-bold text-[#fffdf8]" type="button">Continue</button><button className="rounded-[.4rem] border border-[#e1d9cc] bg-[#fffdf8] px-[.95rem] py-[.58rem]" type="button">Save draft</button></div><p className="m-0 text-xs text-[#657167]">Prototype only — documents are not uploaded or independently verified.</p></form></section><aside className="grid content-start gap-4"><section className={`${card} p-[1.35rem]`}><p className="m-0 text-[.73rem] tracking-[.08em] text-[#657167]">VERIFICATION FLOW</p><ol className="mt-4 grid gap-3 pl-4 text-[.9rem] text-[#566458]"><li>Apply</li><li>Submit credentials</li><li>Admin review</li><li>Approve</li><li>Profile published</li></ol></section><section className={`${card} p-[1.35rem]`}><p className="m-0 text-[.73rem] tracking-[.08em] text-[#657167]">DOCUMENTS SUBMITTED</p><strong className="mt-[.7rem] block">0 of 5</strong></section></aside></div></div></main>
}
