import { SiteHeader } from '@/components/site-header'
import { TherapistPortalTabs } from '@/components/therapist-portal-tabs'

const windows = [['Monday', '05:00 PM', '09:00 PM'], ['Wednesday', '05:00 PM', '09:00 PM'], ['Saturday', '10:00 AM', '03:00 PM']]
const slots = [['WED, SEP 23', ['5:00 PM', '5:50 PM', '6:40 PM', '7:30 PM']], ['SAT, SEP 26', ['10:00 AM', '10:50 AM', '11:40 AM', '12:30 PM', '1:20 PM', '2:10 PM']], ['MON, SEP 28', ['5:00 PM', '5:50 PM', '6:40 PM', '7:30 PM']]]

export default function AvailabilityPage() {
  const card = 'rounded-[1.25rem] border border-[#e1d9cc] bg-[#fffdf8] p-6'
  const input = 'min-h-[2.3rem] rounded-[.4rem] border border-[#e1d9cc] bg-[#fffdf8] px-[.7rem] py-[.55rem] text-[#112f22] shadow-[0_2px_3px_#382c1d12]'
  return <main className="min-h-screen bg-[#fbf7ee] text-[#112f22]"><SiteHeader active="therapists-portal" /><div className="mx-auto w-[min(1240px,calc(100%_-_2.5rem))] pt-[.6rem] max-md:w-[calc(100%_-_2rem)]"><TherapistPortalTabs active="availability" /><div className="mt-6 grid grid-cols-2 gap-6 max-md:grid-cols-1"><section className={card}><h1 className="m-0 font-[family-name:var(--happi-font-title)] text-[1.35rem]">General availability</h1><p className="mt-2 mb-5 text-[.87rem] leading-[1.55] text-[#566458]">Set the hours you are open each week. Happi turns them into 50-minute bookable slots and blocks any slot that is already taken or outside these hours.</p>{windows.map(([day, from, to]) => <article className="my-3 grid grid-cols-[1.2fr_1.2fr_1.2fr_.7fr] items-end gap-[.7rem] rounded-[.8rem] border border-[#e1d9cc] p-3 max-md:grid-cols-1" key={day}><label className="grid gap-[.35rem] text-[.72rem] text-[#657167]">Day<select className={input} defaultValue={day}><option>{day}</option></select></label><label className="grid gap-[.35rem] text-[.72rem] text-[#657167]">From<input className={input} defaultValue={from} /></label><label className="grid gap-[.35rem] text-[.72rem] text-[#657167]">To<input className={input} defaultValue={to} /></label><button className="border-0 bg-transparent text-[.73rem]" type="button">Remove</button></article>)}<button className="mt-[.2rem] rounded-[.4rem] border border-[#e1d9cc] bg-[#fffdf8] px-[.95rem] py-[.58rem]" type="button">Add availability window</button><button className="mt-[1.2rem] block rounded-[.4rem] border border-[#195438] bg-[#195438] px-[.95rem] py-[.58rem] font-bold text-[#fffdf8]" type="button">Save availability</button></section><aside className={card}><h1 className="m-0 font-[family-name:var(--happi-font-title)] text-[1.35rem]">Generated slots (next 7 days)</h1><p className="mt-2 mb-5 text-[.87rem] leading-[1.55] text-[#566458]">Monday: 5:00 PM–9:00 PM · Wednesday: 5:00 PM–9:00 PM · Saturday: 10:00 AM–3:00 PM</p>{slots.map(([date, times]) => <div className="mt-[1.1rem]" key={date as string}><span className="text-[.72rem] tracking-[.08em] text-[#657167]">{date as string}</span><p className="mt-[.55rem] flex flex-wrap gap-2">{(times as string[]).map((time) => <button className="rounded-[.45rem] border border-[#e1d9cc] bg-[#fffdf8] px-[.65rem] py-[.35rem] text-[.73rem]" type="button" key={time}>{time}</button>)}</p></div>)}</aside></div></div></main>
}
